package com.makemytrip.enums;
public enum CancellationReason {
    CHANGE_OF_PLANS, FOUND_BETTER_PRICE, MEDICAL_EMERGENCY, VISA_ISSUES,
    WEATHER_CONDITIONS, WORK_COMMITMENT, PERSONAL_EMERGENCY, DUPLICATE_BOOKING, OTHER
}
